//! Tools served by [Model Context Protocol](https://modelcontextprotocol.io)
//! servers.
//!
//! Enabled by the `mcp` Cargo feature, which requires Rust 1.88 (the minimum
//! supported version of [`rmcp`], the official Rust MCP SDK). The rest of the
//! crate keeps its own, lower minimum.
//!
//! [`McpTools`] binds an MCP server's tool catalog to the [`Peer`] it was read
//! from. One value covers every tool on the server, so an application registers
//! a whole catalog without writing a handler per tool:
//!
//! - [`McpTools::definitions`] advertises the catalog as handler-free
//!   [`ToolDefinition`]s for applications that run their own tool loop, such as
//!   [`stream_wire_events`](crate::RequestBuilder::stream_wire_events) proxies.
//!   [`McpTools::call`] then executes any call the model makes and returns the
//!   tool-result [`Message`] to send back.
//! - [`McpTools::tools`] turns the catalog into [`Tool`]s for the
//!   auto-executing methods such as [`generate`](crate::RequestBuilder::generate).
//!
//! # What is preserved
//!
//! - **Schemas.** Each tool's `inputSchema` is advertised exactly as the server
//!   declared it. It is not normalized the way schemas generated by
//!   [`Tool::handler`] are, and arguments are not validated locally: the server
//!   owns its schema and validates its own input.
//! - **Results.** A successful call's `structuredContent` is sent to the model
//!   as JSON when present. Otherwise its text content is sent verbatim.
//!   Content the model cannot receive as a tool result (images, audio, binary
//!   resources) is reported as [`McpError::UnsupportedContent`] instead of being
//!   dropped.
//! - **Errors.** A result with `isError: true` is a domain failure the model
//!   should see: it becomes a [`Message::tool_error`]. A transport, protocol, or
//!   cancellation failure is an [`McpError`], so the application decides
//!   whether to retry, report it to the model, or abort the turn.
//!
//! # Credentials and isolation
//!
//! An [`McpTools`] holds nothing but the peer it was built from and that
//! peer's catalog. Authentication is a property of the transport the
//! application connected with. A server that authorizes each caller should be
//! reached through a peer built with that caller's credentials, and the
//! resulting [`McpTools`] attached to that caller's requests only (for example
//! with [`RequestBuilder::tool_definitions`](crate::RequestBuilder::tool_definitions)
//! or [`RequestBuilder::tools`](crate::RequestBuilder::tools)). Cloning shares
//! both the peer and catalog. The application must keep the original value,
//! its clones, and the tools built from them scoped to the same authenticated
//! caller or credential context. This module has no global cache and does not
//! enforce caller identity.
//!
//! # Cancellation
//!
//! [`McpTools::call_until`] races a call against a caller-supplied future,
//! such as `CancellationToken::cancelled()`, and returns
//! [`McpError::Cancelled`] as soon as that future completes:
//!
//! - Cancellation is checked before the call is dispatched and while it waits
//!   to be queued on the session, so a caller that is already cancelled never
//!   sends the call.
//! - Once the call has been sent, the server is sent `notifications/cancelled`
//!   for it from a background task (on the current Tokio runtime), so a stalled
//!   session cannot delay the caller's return.
//!
//! MCP cancellation is advisory: the server may already have finished, or may
//! finish the work anyway, so a cancelled call to a tool with side effects can
//! still have taken effect. Dropping a [`McpTools::call`] future stops waiting
//! for the result without notifying the server.
//!
//! # Example
//!
//! ```rust,no_run
//! use rai_sdk::mcp::McpTools;
//! use rai_sdk::mcp::rmcp::{RoleClient, service::Peer};
//! use rai_sdk::{Client, client::ModelReady};
//!
//! # async fn run(
//! #     client: &Client<ModelReady>,
//! #     peer: Peer<RoleClient>,
//! # ) -> Result<(), Box<dyn std::error::Error>> {
//! // `peer` is a connected MCP client session, authenticated as the caller.
//! let catalog = McpTools::discover(peer).await?;
//!
//! let response = client
//!     .request()
//!     .tools(catalog.tools())
//!     .prompt("Which symbols moved most today?")
//!     .generate()
//!     .await?;
//! println!("{}", response.text());
//! # Ok(())
//! # }
//! ```

use std::{collections::HashSet, future::Future, sync::Arc};

use futures::future::{Either, select};
use rmcp::{
    RoleClient, ServiceError,
    model::{
        CallToolRequest, CallToolRequestParams, CallToolResult, CancelledNotification,
        CancelledNotificationParam, ClientRequest, ContentBlock, PaginatedRequestParams, RequestId,
        ResourceContents, ServerResult,
    },
    service::{Peer, PeerRequestOptions},
};

/// Re-export of the [`rmcp`] crate this module is built on, so applications
/// can name its types without depending on a second, possibly mismatched,
/// copy.
pub use rmcp;

use crate::{
    message::{Message, ToolCall, ToolDefinition},
    tool::{Tool, ToolOutput},
};

/// Errors from reading or calling an MCP tool catalog.
///
/// These are failures of the exchange with the server. A tool that ran and
/// reported a failure (`isError: true`) is not an error here: it is returned as
/// a tool-error [`Message`] for the model.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum McpError {
    /// The request failed in transport or at the protocol level, including a
    /// JSON-RPC error response from the server.
    #[error("MCP request failed: {0}")]
    Service(#[from] ServiceError),

    /// The catalog contains a tool name that is empty or appears more than once.
    #[error("invalid MCP tool catalog: {0}")]
    InvalidCatalog(String),

    /// The model called a tool that is not in this catalog.
    #[error("MCP tool not found: {name}")]
    ToolNotFound {
        /// Tool name the model called.
        name: String,
    },

    /// The tool returned content that cannot be sent to the model as a tool
    /// result.
    #[error("MCP tool '{tool}' returned {kind} content, which cannot be sent as a tool result")]
    UnsupportedContent {
        /// Name of the tool on the server.
        tool: String,
        /// The content kind, such as `image` or `audio`.
        kind: &'static str,
    },

    /// The server answered the call with something other than a final result,
    /// such as an `input_required` round or a task handle.
    #[error("MCP tool '{tool}' returned an unsupported {kind} response")]
    UnsupportedResponse {
        /// Name of the tool on the server.
        tool: String,
        /// The response kind.
        kind: &'static str,
    },

    /// The caller's cancellation signal completed before the server answered.
    #[error("MCP tool call '{tool}' was cancelled")]
    Cancelled {
        /// Name of the tool on the server.
        tool: String,
    },
}

/// Convert an MCP tool into a [`ToolDefinition`], keeping its name,
/// description and input schema unchanged.
pub fn tool_definition(tool: &rmcp::model::Tool) -> ToolDefinition {
    ToolDefinition {
        name: tool.name.to_string(),
        description: tool.description.as_ref().map(ToString::to_string),
        input_schema: serde_json::Value::Object(tool.input_schema.as_ref().clone()),
    }
}

/// Convert a final MCP tool result into the [`ToolOutput`] sent to the model.
///
/// `structuredContent`, when present, is sent as JSON. Otherwise text blocks and
/// text resources are sent verbatim (joined by newlines when there are several)
/// and resource links are sent as their JSON form. `isError: true` produces an
/// error output. `tool` names the tool in [`McpError::UnsupportedContent`].
pub fn tool_output(tool: &str, result: &CallToolResult) -> Result<ToolOutput, McpError> {
    let content = match &result.structured_content {
        Some(structured) => {
            serde_json::to_string(structured).map_err(|_| unsupported(tool, "structured"))?
        }
        None => {
            let mut parts = Vec::with_capacity(result.content.len());
            for block in &result.content {
                parts.push(block_text(tool, block)?);
            }
            parts.join("\n")
        }
    };

    Ok(if result.is_error == Some(true) {
        ToolOutput::error(content)
    } else {
        ToolOutput::success(content)
    })
}

fn block_text(tool: &str, block: &ContentBlock) -> Result<String, McpError> {
    match block {
        ContentBlock::Text(text) => Ok(text.text.clone()),
        ContentBlock::Resource(embedded) => match &embedded.resource {
            ResourceContents::TextResourceContents { text, .. } => Ok(text.clone()),
            ResourceContents::BlobResourceContents { .. } => {
                Err(unsupported(tool, "binary resource"))
            }
            _ => Err(unsupported(tool, "resource")),
        },
        ContentBlock::ResourceLink(link) => {
            serde_json::to_string(link).map_err(|_| unsupported(tool, "resource link"))
        }
        ContentBlock::Image(_) => Err(unsupported(tool, "image")),
        ContentBlock::Audio(_) => Err(unsupported(tool, "audio")),
        _ => Err(unsupported(tool, "unknown")),
    }
}

fn unsupported(tool: &str, kind: &'static str) -> McpError {
    McpError::UnsupportedContent {
        tool: tool.to_string(),
        kind,
    }
}

#[derive(Clone)]
struct McpTool {
    /// Name advertised to the model.
    name: String,
    /// The tool as the server declared it; its name is the one called.
    remote: rmcp::model::Tool,
}

/// An MCP server's tool catalog bound to a client session.
///
/// Cheap to clone: clones share the underlying [`Peer`] and catalog. See the
/// [module documentation](self) for result, error, credential and cancellation
/// semantics.
#[derive(Clone)]
pub struct McpTools {
    peer: Peer<RoleClient>,
    tools: Arc<[McpTool]>,
}

impl std::fmt::Debug for McpTools {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("McpTools")
            .field(
                "tools",
                &self.tools.iter().map(|tool| &tool.name).collect::<Vec<_>>(),
            )
            .finish_non_exhaustive()
    }
}

impl McpTools {
    /// Read the server's full tool catalog, following pagination, and bind it
    /// to `peer`.
    ///
    /// A server that hands back a cursor it already returned is rejected with
    /// [`McpError::InvalidCatalog`] rather than paged forever. Discovery has no
    /// deadline of its own: bound it with the application's timeout (for
    /// example `tokio::time::timeout`) or a timeout configured on the
    /// transport. To cap how much of a catalog is read, page it with
    /// [`Peer::list_tools`] and bind the result with
    /// [`from_catalog`](Self::from_catalog).
    pub async fn discover(peer: Peer<RoleClient>) -> Result<Self, McpError> {
        let mut tools = Vec::new();
        let mut cursors = HashSet::new();
        let mut cursor = None;
        loop {
            let mut params = PaginatedRequestParams::default();
            params.cursor = cursor;
            let page = peer.list_tools(Some(params)).await?;
            tools.extend(page.tools);
            match page.next_cursor {
                None => break,
                Some(next) if !cursors.insert(next.clone()) => {
                    return Err(McpError::InvalidCatalog(format!(
                        "server repeated pagination cursor '{next}'"
                    )));
                }
                Some(next) => cursor = Some(next),
            }
        }
        Self::from_catalog(peer, tools)
    }

    /// Bind an already-fetched catalog to `peer`.
    ///
    /// Use this to reuse a catalog the application has cached for the same
    /// server and caller or credential context. The application must ensure the
    /// catalog matches the peer's authorization context; this method does not
    /// verify that association. Fails if a tool name is empty or repeated.
    pub fn from_catalog<I>(peer: Peer<RoleClient>, tools: I) -> Result<Self, McpError>
    where
        I: IntoIterator<Item = rmcp::model::Tool>,
    {
        let tools = tools
            .into_iter()
            .map(|remote| McpTool {
                name: remote.name.to_string(),
                remote,
            })
            .collect::<Vec<_>>();
        check_names(&tools)?;
        Ok(Self {
            peer,
            tools: tools.into(),
        })
    }

    /// Keep only the tools for which `keep` returns `true`.
    pub fn filter<F>(self, mut keep: F) -> Self
    where
        F: FnMut(&rmcp::model::Tool) -> bool,
    {
        let tools = self
            .tools
            .iter()
            .filter(|tool| keep(&tool.remote))
            .cloned()
            .collect::<Vec<_>>();
        Self {
            peer: self.peer,
            tools: tools.into(),
        }
    }

    /// Choose the name each tool is advertised to the model under.
    ///
    /// Calls are still sent to the server under the tool's own name. Use this
    /// to prefix tools from several servers, or to keep names a model or
    /// prompt already relies on. Fails if two tools end up with the same name
    /// or a name is empty.
    pub fn rename<F>(self, mut rename: F) -> Result<Self, McpError>
    where
        F: FnMut(&rmcp::model::Tool) -> String,
    {
        let tools = self
            .tools
            .iter()
            .map(|tool| McpTool {
                name: rename(&tool.remote),
                remote: tool.remote.clone(),
            })
            .collect::<Vec<_>>();
        check_names(&tools)?;
        Ok(Self {
            peer: self.peer,
            tools: tools.into(),
        })
    }

    /// The session calls are sent on.
    pub fn peer(&self) -> &Peer<RoleClient> {
        &self.peer
    }

    /// Number of tools in the catalog.
    pub fn len(&self) -> usize {
        self.tools.len()
    }

    /// Whether the catalog is empty.
    pub fn is_empty(&self) -> bool {
        self.tools.is_empty()
    }

    /// Whether `name` is a tool in this catalog, by its advertised name.
    ///
    /// Applications combining several catalogs, or a catalog with local tools,
    /// use this to route a model's tool call.
    pub fn contains(&self, name: &str) -> bool {
        self.find(name).is_some()
    }

    /// The server's declaration of the tool advertised as `name`, including
    /// its title, annotations and output schema.
    pub fn remote_tool(&self, name: &str) -> Option<&rmcp::model::Tool> {
        self.find(name).map(|tool| &tool.remote)
    }

    /// The catalog as handler-free tool definitions, in server order.
    pub fn definitions(&self) -> Vec<ToolDefinition> {
        self.tools
            .iter()
            .map(|tool| ToolDefinition {
                name: tool.name.clone(),
                ..tool_definition(&tool.remote)
            })
            .collect()
    }

    /// The catalog as executable [`Tool`]s for the auto-executing request
    /// methods.
    ///
    /// Each tool calls the server through this catalog's peer. Inside the tool
    /// loop every failure is reported to the model, as for any tool handler:
    /// an `isError` result is sent as returned, and an [`McpError`] is sent as
    /// a tool error describing it.
    pub fn tools(&self) -> Vec<Tool> {
        self.tools
            .iter()
            .map(|tool| {
                let catalog = self.clone();
                let name = tool.name.clone();
                Tool::from_definition(
                    ToolDefinition {
                        name: tool.name.clone(),
                        ..tool_definition(&tool.remote)
                    },
                    move |arguments, _ctx| {
                        let catalog = catalog.clone();
                        let name = name.clone();
                        async move {
                            match catalog
                                .output(&name, arguments, None::<std::future::Pending<()>>)
                                .await
                            {
                                Ok(output) => Ok(output),
                                Err(error) => Ok(ToolOutput::error(serde_json::to_string(
                                    &serde_json::json!({ "error": error.to_string() }),
                                )?)),
                            }
                        }
                    },
                )
            })
            .collect()
    }

    /// Execute a tool call from the model and return the tool-result message.
    ///
    /// Arguments that are not a JSON object (or `null`) are rejected without
    /// contacting the server, as a tool-error message the model can correct.
    pub async fn call(&self, call: &ToolCall) -> Result<Message, McpError> {
        self.call_inner(call, None::<std::future::Pending<()>>)
            .await
    }

    /// [`call`](Self::call), abandoned when `cancelled` completes first.
    ///
    /// A call that was already sent is cancelled on the server with
    /// `notifications/cancelled`, and [`McpError::Cancelled`] is returned
    /// without waiting for that notification to be delivered. See the
    /// [module documentation](self#cancellation) for what cancellation does
    /// and does not guarantee.
    pub async fn call_until<C>(&self, call: &ToolCall, cancelled: C) -> Result<Message, McpError>
    where
        C: Future<Output = ()>,
    {
        self.call_inner(call, Some(cancelled)).await
    }

    async fn call_inner<C>(
        &self,
        call: &ToolCall,
        cancelled: Option<C>,
    ) -> Result<Message, McpError>
    where
        C: Future<Output = ()>,
    {
        let output = self
            .output(&call.name, call.arguments.clone(), cancelled)
            .await?;
        Ok(output.into_message(call.id.clone()))
    }

    async fn output<C>(
        &self,
        name: &str,
        arguments: serde_json::Value,
        cancelled: Option<C>,
    ) -> Result<ToolOutput, McpError>
    where
        C: Future<Output = ()>,
    {
        let tool = self.find(name).ok_or_else(|| McpError::ToolNotFound {
            name: name.to_string(),
        })?;
        let remote_name = tool.remote.name.clone();

        let mut params = CallToolRequestParams::new(remote_name.clone());
        match arguments {
            serde_json::Value::Object(arguments) => params = params.with_arguments(arguments),
            serde_json::Value::Null => {}
            other => return Ok(argument_error(name, &other)),
        }

        let request = ClientRequest::CallToolRequest(CallToolRequest::new(params));
        let send = self
            .peer
            .send_cancellable_request(request, PeerRequestOptions::no_options());
        let response = match cancelled {
            None => send.await?.await_response().await?,
            Some(cancelled) => {
                let mut cancelled = std::pin::pin!(cancelled);
                // Cancellation is polled first in both races. Until `send`
                // completes nothing has been queued for the server, so a
                // caller that is already cancelled, or is cancelled while the
                // session is backed up, never dispatches the call.
                let handle = match select(cancelled.as_mut(), std::pin::pin!(send)).await {
                    Either::Left(((), _)) => {
                        return Err(cancelled_error(&self.peer, &remote_name, None));
                    }
                    Either::Right((handle, _)) => handle?,
                };
                let request_id = handle.id.clone();
                match select(cancelled, std::pin::pin!(handle.await_response())).await {
                    Either::Left(((), _)) => {
                        return Err(cancelled_error(&self.peer, &remote_name, Some(request_id)));
                    }
                    Either::Right((response, _)) => response?,
                }
            }
        };

        match response {
            ServerResult::CallToolResult(result) => tool_output(&remote_name, &result),
            ServerResult::InputRequiredResult(_) => Err(McpError::UnsupportedResponse {
                tool: remote_name.to_string(),
                kind: "input_required",
            }),
            ServerResult::CreateTaskResult(_) => Err(McpError::UnsupportedResponse {
                tool: remote_name.to_string(),
                kind: "task",
            }),
            _ => Err(McpError::Service(ServiceError::UnexpectedResponse)),
        }
    }

    fn find(&self, name: &str) -> Option<&McpTool> {
        self.tools.iter().find(|tool| tool.name == name)
    }
}

/// The error for a cancelled call. When the request had been dispatched, the
/// server is told in a background task, so a slow or stalled session cannot
/// delay the caller's cancellation.
fn cancelled_error(peer: &Peer<RoleClient>, tool: &str, request_id: Option<RequestId>) -> McpError {
    if let Some(request_id) = request_id {
        let notification = CancelledNotification::new(CancelledNotificationParam::new(
            Some(request_id),
            Some("cancelled by the client".to_string()),
        ));
        match tokio::runtime::Handle::try_current() {
            Ok(runtime) => {
                let peer = peer.clone();
                let tool = tool.to_string();
                runtime.spawn(async move {
                    if let Err(error) = peer.send_notification(notification.into()).await {
                        tracing::debug!(%tool, %error, "failed to send MCP cancellation");
                    }
                });
            }
            Err(_) => tracing::debug!(%tool, "no Tokio runtime to send MCP cancellation on"),
        }
    }
    McpError::Cancelled {
        tool: tool.to_string(),
    }
}

fn check_names(tools: &[McpTool]) -> Result<(), McpError> {
    let mut seen = HashSet::with_capacity(tools.len());
    for tool in tools {
        if tool.name.trim().is_empty() {
            return Err(McpError::InvalidCatalog(format!(
                "tool '{}' has an empty name",
                tool.remote.name
            )));
        }
        if !seen.insert(tool.name.as_str()) {
            return Err(McpError::InvalidCatalog(format!(
                "tool name '{}' appears more than once",
                tool.name
            )));
        }
    }
    Ok(())
}

fn argument_error(name: &str, arguments: &serde_json::Value) -> ToolOutput {
    let kind = match arguments {
        serde_json::Value::Bool(_) => "boolean",
        serde_json::Value::Number(_) => "number",
        serde_json::Value::String(_) => "string",
        serde_json::Value::Array(_) => "array",
        serde_json::Value::Null | serde_json::Value::Object(_) => "object",
    };
    ToolOutput::error(
        serde_json::json!({
            "error": {
                "type": "tool_argument_validation",
                "tool": name,
                "retryable": true,
                "message": "Tool arguments failed validation. Call the tool again with corrected arguments.",
                "summary": format!("arguments must be a JSON object, not a {kind}"),
                "issues": [],
            }
        })
        .to_string(),
    )
}
