//! Tools served by [Model Context Protocol](https://modelcontextprotocol.io)
//! servers.
//!
//! Enabled by the `mcp` Cargo feature, which requires Rust 1.88 (the minimum
//! supported version of [`rmcp`], the official Rust MCP SDK). The rest of the
//! crate keeps its own, lower minimum.
//!
//! [`McpTools`] binds an MCP server's tool catalog to the [`Peer`] it was read
//! from. One value covers every tool on the server, so an application registers
//! a whole catalog without writing a handler per tool:
//!
//! - [`McpTools::definitions`] advertises the catalog as handler-free
//!   [`ToolDefinition`]s for applications that run their own tool loop, such as
//!   [`stream_wire_events`](crate::RequestBuilder::stream_wire_events) proxies.
//!   [`McpTools::call`] then executes any call the model makes and returns the
//!   tool-result [`Message`] to send back. [`McpTools::call_result`] returns the
//!   complete MCP result before model conversion, for structured UI events.
//! - [`McpTools::tools`] turns the catalog into [`Tool`]s for the
//!   auto-executing methods such as [`generate`](crate::RequestBuilder::generate).
//!
//! # What is preserved
//!
//! - **Schemas.** Each tool's `inputSchema` is advertised exactly as the server
//!   declared it. It is not normalized the way schemas generated by
//!   [`Tool::handler`] are, and arguments are not validated locally: the server
//!   owns its schema and validates its own input.
//! - **Validation.** Successful structured results are checked against their
//!   declared output schemas. Schema work runs off the async executor, with
//!   bounded concurrency, and shares the call deadline.
//! - **Results.** A successful call's `structuredContent` is sent to the model
//!   as JSON when present. Otherwise its text content is sent verbatim.
//!   Content the model cannot receive as a tool result (images, audio, binary
//!   resources) is reported as [`McpError::UnsupportedContent`] instead of being
//!   dropped.
//! - **Errors.** A result with `isError: true` is a domain failure the model
//!   should see: it becomes a [`Message::tool_error`]. A transport, protocol, or
//!   cancellation failure is an [`McpError`], so the application decides
//!   whether to retry, report it to the model, or abort the turn.
//!
//! # Credentials and isolation
//!
//! An [`McpTools`] holds nothing but the peer it was built from and that
//! peer's catalog. Authentication is a property of the transport the
//! application connected with. A server that authorizes each caller should be
//! reached through a peer built with that caller's credentials, and the
//! resulting [`McpTools`] attached to that caller's requests only (for example
//! with [`RequestBuilder::tool_definitions`](crate::RequestBuilder::tool_definitions)
//! or [`RequestBuilder::tools`](crate::RequestBuilder::tools)). Cloning shares
//! both the peer and catalog. The application must keep the original value,
//! its clones, and the tools built from them scoped to the same authenticated
//! caller or credential context. This module has no global cache and does not
//! enforce caller identity.
//!
//! # Cancellation
//!
//! [`McpTools::call_until`] races a call against a caller-supplied future,
//! such as `CancellationToken::cancelled()`, and returns
//! [`McpError::Cancelled`] as soon as that future completes:
//!
//! - Cancellation is checked before the call is dispatched and while it waits
//!   to be queued on the session, so a caller that is already cancelled never
//!   sends the call.
//! - Once the call has been sent, the server is sent `notifications/cancelled`
//!   for it from a background task (on the current Tokio runtime), so a stalled
//!   session cannot delay the caller's return.
//!
//! MCP cancellation is advisory: the server may already have finished, or may
//! finish the work anyway, so a cancelled call to a tool with side effects can
//! still have taken effect. Dropping a call future also sends cancellation
//! asynchronously after dispatch. A configured [`RequestOptions::timeout`] covers
//! dispatch and response together; progress notifications do not extend it.
//!
//! # Example
//!
//! ```rust,no_run
//! use rai_sdk::mcp::McpTools;
//! use rai_sdk::mcp::rmcp::{RoleClient, service::Peer};
//! use rai_sdk::{Client, client::ModelReady};
//!
//! # async fn run(
//! #     client: &Client<ModelReady>,
//! #     peer: Peer<RoleClient>,
//! # ) -> Result<(), Box<dyn std::error::Error>> {
//! // `peer` is a connected MCP client session, authenticated as the caller.
//! let catalog = McpTools::discover(peer).await?;
//!
//! let response = client
//!     .request()
//!     .tools(catalog.tools())
//!     .prompt("Which symbols moved most today?")
//!     .generate()
//!     .await?;
//! println!("{}", response.text());
//! # Ok(())
//! # }
//! ```

use std::{collections::HashSet, future::Future, sync::Arc, time::Duration};

use futures::{
    FutureExt,
    future::{BoxFuture, Shared},
};

use rmcp::{
    RoleClient, ServiceError,
    model::{
        CallToolRequest, CallToolRequestParams, CallToolResult, CancelledNotificationParam,
        ClientRequest, ContentBlock, ListToolsRequest, ListToolsResult, PaginatedRequestParams,
        ResourceContents, ServerResult,
    },
    service::{Peer, PeerRequestOptions, RequestHandle},
};

/// Re-export of the [`rmcp`] crate this module is built on, so applications
/// can name its types without depending on a second, possibly mismatched,
/// copy.
pub use rmcp;

mod validation;
pub use validation::{OutputSchemas, SchemaProcessor};

use crate::{
    message::{Message, ToolCall, ToolDefinition},
    tool::{Tool, ToolOutput},
};

/// Errors from reading or calling an MCP tool catalog.
///
/// These are failures of the exchange with the server. A tool that ran and
/// reported a failure (`isError: true`) is not an error here: it is returned as
/// the original MCP result by raw calls, or a tool-error [`Message`] by model calls.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum McpError {
    /// The request failed in transport or at the protocol level, including a
    /// JSON-RPC error response from the server.
    #[error("MCP request failed: {0}")]
    Service(#[from] ServiceError),

    /// The catalog contains a tool name that is empty or appears more than once.
    #[error("invalid MCP tool catalog: {0}")]
    InvalidCatalog(String),

    /// The model called a tool that is not in this catalog.
    #[error("MCP tool not found: {name}")]
    ToolNotFound {
        /// Tool name the model called.
        name: String,
    },

    /// The tool returned content that cannot be sent to the model as a tool
    /// result.
    #[error("MCP tool '{tool}' returned {kind} content, which cannot be sent as a tool result")]
    UnsupportedContent {
        /// Name of the tool on the server.
        tool: String,
        /// The content kind, such as `image` or `audio`.
        kind: &'static str,
    },

    /// The server answered the call with something other than a final result,
    /// such as an `input_required` round or a task handle.
    #[error("MCP tool '{tool}' returned an unsupported {kind} response")]
    UnsupportedResponse {
        /// Name of the tool on the server.
        tool: String,
        /// The response kind.
        kind: &'static str,
    },

    /// The caller's cancellation signal completed before the server answered.
    #[error("MCP tool call '{tool}' was cancelled")]
    Cancelled {
        /// Name of the tool on the server.
        tool: String,
    },

    /// A tool declares an output schema that cannot be compiled locally.
    #[error("MCP tool '{tool}' has an invalid output schema")]
    InvalidOutputSchema {
        /// Name of the tool with the invalid declaration.
        tool: String,
    },

    /// A successful tool result does not match its declared output schema.
    #[error("MCP tool '{tool}' output schema violation: {detail}")]
    OutputSchemaViolation {
        /// Name of the tool returning the result.
        tool: String,
        /// Bounded schema diagnostics, without result data.
        detail: String,
    },

    /// Bounded schema processing could not complete.
    #[error("MCP schema processing did not complete")]
    SchemaProcessing,

    /// Arguments supplied to a raw catalog call were neither an object nor null.
    #[error("MCP tool '{tool}' arguments must be an object or null")]
    InvalidArguments {
        /// Name of the tool as advertised by the catalog.
        tool: String,
    },
}

/// Options for one MCP operation, independent of transport and catalog policy.
///
/// A timeout covers both dispatch and the response wait. Progress notifications
/// do not extend it. Cancelling or dropping the operation abandons the wait and
/// sends cancellation asynchronously if dispatch completed.
#[derive(Debug, Clone, Default)]
#[non_exhaustive]
pub struct RequestOptions {
    /// Total budget for dispatch and response, or no deadline when absent.
    pub timeout: Option<Duration>,
}

impl RequestOptions {
    /// One deadline covering the complete operation.
    pub fn with_timeout(timeout: Duration) -> Self {
        Self {
            timeout: Some(timeout),
            ..Self::default()
        }
    }
}

/// Fetch one catalog page without imposing a cache or catalog representation.
///
/// Applications can enforce page, tool and schema limits while keeping only
/// their own catalog. An interrupted page request is cancelled on the server.
pub async fn list_tools(
    peer: &Peer<RoleClient>,
    params: Option<PaginatedRequestParams>,
    options: RequestOptions,
) -> Result<ListToolsResult, ServiceError> {
    let request =
        ClientRequest::ListToolsRequest(ListToolsRequest::with_param(params.unwrap_or_default()));
    match request_inner(peer, request, options, std::future::pending())
        .await
        .map_err(|error| match error {
            RequestFailure::Service(error) => error,
            RequestFailure::Cancelled => ServiceError::Cancelled {
                reason: Some("cancelled by the client".to_owned()),
            },
        })? {
        ServerResult::ListToolsResult(result) => Ok(result),
        _ => Err(ServiceError::UnexpectedResponse),
    }
}

/// Call a tool and retain its complete MCP result before model conversion.
///
/// Content blocks, `structuredContent`, `_meta` and `isError` are unchanged.
/// No catalog is retained or fetched; applications with their own catalog must
/// check names and authorization before calling. Transport and protocol errors
/// remain typed, and input-required rounds and task handles are unsupported.
pub async fn call_tool(
    peer: &Peer<RoleClient>,
    params: CallToolRequestParams,
    options: RequestOptions,
) -> Result<CallToolResult, McpError> {
    call_tool_until(peer, params, options, std::future::pending()).await
}

/// [`call_tool`], abandoned when `cancelled` completes first.
///
/// A ready signal prevents dispatch. A dispatched request is cancelled from a
/// background task, so notification delivery never delays the caller's return.
pub async fn call_tool_until<C>(
    peer: &Peer<RoleClient>,
    params: CallToolRequestParams,
    options: RequestOptions,
    cancelled: C,
) -> Result<CallToolResult, McpError>
where
    C: Future<Output = ()>,
{
    let name = params.name.to_string();
    let request = ClientRequest::CallToolRequest(CallToolRequest::new(params));
    let response = request_inner(peer, request, options, cancelled)
        .await
        .map_err(|error| match error {
            RequestFailure::Cancelled => McpError::Cancelled { tool: name.clone() },
            RequestFailure::Service(error) => McpError::Service(error),
        })?;
    match response {
        ServerResult::CallToolResult(result) => Ok(result),
        ServerResult::InputRequiredResult(_) => Err(McpError::UnsupportedResponse {
            tool: name,
            kind: "input_required",
        }),
        ServerResult::CreateTaskResult(_) => Err(McpError::UnsupportedResponse {
            tool: name,
            kind: "task",
        }),
        _ => Err(McpError::Service(ServiceError::UnexpectedResponse)),
    }
}

#[derive(Debug, thiserror::Error)]
enum RequestFailure {
    #[error(transparent)]
    Service(#[from] ServiceError),
    #[error("request cancelled by the caller")]
    Cancelled,
}

async fn request_inner<C>(
    peer: &Peer<RoleClient>,
    request: ClientRequest,
    options: RequestOptions,
    cancelled: C,
) -> Result<ServerResult, RequestFailure>
where
    C: Future<Output = ()>,
{
    let mut cancelled = std::pin::pin!(cancelled);
    if futures::poll!(cancelled.as_mut()).is_ready() {
        return Err(RequestFailure::Cancelled);
    }
    if options.timeout.is_some_and(|timeout| timeout.is_zero()) {
        return Err(ServiceError::Timeout {
            timeout: Duration::ZERO,
        }
        .into());
    }
    let deadline = options
        .timeout
        .and_then(|timeout| tokio::time::Instant::now().checked_add(timeout));
    let exchange = async {
        // rai owns the timer: rmcp's response timer excludes dispatch and waits
        // for cancellation delivery before returning its timeout error.
        let mut send = std::pin::pin!(
            peer.send_cancellable_request(request, PeerRequestOptions::no_options())
        );
        let handle = futures::future::poll_fn(|cx| {
            if deadline.is_some_and(|deadline| tokio::time::Instant::now() >= deadline) {
                return std::task::Poll::Ready(Err(ServiceError::Timeout {
                    timeout: options.timeout.unwrap_or_default(),
                }));
            }
            send.as_mut().poll(cx)
        })
        .await?;
        let mut guard = CancelOnDrop {
            handle,
            complete: false,
        };
        let response = (&mut guard.handle.rx).await;
        guard.complete = true;
        response
            .map_err(|_| ServiceError::TransportClosed)?
            .map_err(RequestFailure::Service)
    };
    let expired = async {
        match deadline {
            Some(deadline) => tokio::time::sleep_until(deadline).await,
            None => std::future::pending().await,
        }
    };
    tokio::select! {
        biased;
        () = cancelled => Err(RequestFailure::Cancelled),
        () = expired => Err(ServiceError::Timeout { timeout: options.timeout.unwrap_or_default() }.into()),
        response = exchange => response,
    }
}

struct CancelOnDrop {
    handle: RequestHandle<RoleClient>,
    complete: bool,
}

impl Drop for CancelOnDrop {
    fn drop(&mut self) {
        if self.complete
            || !matches!(
                self.handle.rx.try_recv(),
                Err(tokio::sync::oneshot::error::TryRecvError::Empty)
            )
        {
            return;
        }
        let Ok(runtime) = tokio::runtime::Handle::try_current() else {
            return;
        };
        let peer = self.handle.peer.clone();
        let id = self.handle.id.clone();
        runtime.spawn(async move {
            let params = CancelledNotificationParam::new(
                Some(id),
                Some("cancelled by the client".to_owned()),
            );
            if peer.notify_cancelled(params).await.is_err() {
                tracing::debug!("MCP cancellation notification was not delivered");
            }
        });
    }
}

/// Convert an MCP tool into a [`ToolDefinition`], keeping its name,
/// description and input schema unchanged.
pub fn tool_definition(tool: &rmcp::model::Tool) -> ToolDefinition {
    ToolDefinition {
        name: tool.name.to_string(),
        description: tool.description.as_ref().map(ToString::to_string),
        input_schema: serde_json::Value::Object(tool.input_schema.as_ref().clone()),
    }
}

/// Convert a final MCP tool result into the [`ToolOutput`] sent to the model.
///
/// `structuredContent`, when present, is sent as JSON. Otherwise text blocks and
/// text resources are sent verbatim (joined by newlines when there are several)
/// and resource links are sent as their JSON form. `isError: true` produces an
/// error output. `tool` names the tool in [`McpError::UnsupportedContent`].
pub fn tool_output(tool: &str, result: &CallToolResult) -> Result<ToolOutput, McpError> {
    let content = match &result.structured_content {
        Some(structured) => {
            serde_json::to_string(structured).map_err(|_| unsupported(tool, "structured"))?
        }
        None => {
            let mut parts = Vec::with_capacity(result.content.len());
            for block in &result.content {
                parts.push(block_text(tool, block)?);
            }
            parts.join("\n")
        }
    };

    Ok(if result.is_error == Some(true) {
        ToolOutput::error(content)
    } else {
        ToolOutput::success(content)
    })
}

fn block_text(tool: &str, block: &ContentBlock) -> Result<String, McpError> {
    match block {
        ContentBlock::Text(text) => Ok(text.text.clone()),
        ContentBlock::Resource(embedded) => match &embedded.resource {
            ResourceContents::TextResourceContents { text, .. } => Ok(text.clone()),
            ResourceContents::BlobResourceContents { .. } => {
                Err(unsupported(tool, "binary resource"))
            }
            _ => Err(unsupported(tool, "resource")),
        },
        ContentBlock::ResourceLink(link) => {
            serde_json::to_string(link).map_err(|_| unsupported(tool, "resource link"))
        }
        ContentBlock::Image(_) => Err(unsupported(tool, "image")),
        ContentBlock::Audio(_) => Err(unsupported(tool, "audio")),
        _ => Err(unsupported(tool, "unknown")),
    }
}

fn unsupported(tool: &str, kind: &'static str) -> McpError {
    McpError::UnsupportedContent {
        tool: tool.to_string(),
        kind,
    }
}

#[derive(Clone)]
struct McpTool {
    /// Name advertised to the model.
    name: String,
    /// The tool as the server declared it; its name is the one called.
    remote: rmcp::model::Tool,
    schema: Arc<std::sync::OnceLock<SchemaFlight>>,
}

impl McpTool {
    async fn output_schemas(
        &self,
        processor: &Arc<SchemaProcessor>,
    ) -> Result<Option<Arc<OutputSchemas>>, McpError> {
        let schemas = if let Some(schema) = &self.remote.output_schema {
            let flight = self.schema.get_or_init(|| {
                let processor = Arc::clone(processor);
                let schema = serde_json::Value::Object(schema.as_ref().clone());
                let tool_name = self.name.clone();
                // Compilation belongs to the catalog, not the first caller's
                // budget. Each waiter has its own deadline and cancellation.
                let task = tokio::spawn(async move {
                    processor
                        .compile(vec![(tool_name, schema)], RequestOptions::default())
                        .await
                });
                async move {
                    match task.await {
                        Ok(Ok(schemas)) => Ok(Arc::new(schemas)),
                        Ok(Err(McpError::InvalidOutputSchema { tool })) => {
                            Err(SchemaFailure::Invalid(tool))
                        }
                        _ => Err(SchemaFailure::Processing),
                    }
                }
                .boxed()
                .shared()
            });
            Some(flight.clone().await.map_err(SchemaFailure::into_error)?)
        } else {
            None
        };
        Ok(schemas)
    }
}

type SchemaFlight = Shared<BoxFuture<'static, Result<Arc<OutputSchemas>, SchemaFailure>>>;

#[derive(Clone)]
enum SchemaFailure {
    Invalid(String),
    Processing,
}

impl SchemaFailure {
    fn into_error(self) -> McpError {
        match self {
            Self::Invalid(tool) => McpError::InvalidOutputSchema { tool },
            Self::Processing => McpError::SchemaProcessing,
        }
    }
}

/// An MCP server's tool catalog bound to a client session.
///
/// Cheap to clone: clones share the underlying [`Peer`] and catalog. See the
/// [module documentation](self) for result, error, credential and cancellation
/// semantics.
#[derive(Clone)]
pub struct McpTools {
    peer: Peer<RoleClient>,
    tools: Arc<[McpTool]>,
    schema_processor: Arc<SchemaProcessor>,
}

impl std::fmt::Debug for McpTools {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("McpTools")
            .field(
                "tools",
                &self.tools.iter().map(|tool| &tool.name).collect::<Vec<_>>(),
            )
            .finish_non_exhaustive()
    }
}

impl McpTools {
    /// Read the server's full tool catalog, following pagination, and bind it
    /// to `peer`.
    ///
    /// A server that hands back a cursor it already returned is rejected with
    /// [`McpError::InvalidCatalog`] rather than paged forever. Discovery has no
    /// deadline of its own: bound it with the application's timeout (for
    /// example `tokio::time::timeout`) or a timeout configured on the
    /// transport. To cap how much of a catalog is read, page it with
    /// [`list_tools`] and bind the result with
    /// [`from_catalog`](Self::from_catalog).
    pub async fn discover(peer: Peer<RoleClient>) -> Result<Self, McpError> {
        let mut tools = Vec::new();
        let mut cursors = HashSet::new();
        let mut cursor = None;
        loop {
            let mut params = PaginatedRequestParams::default();
            params.cursor = cursor;
            let page = list_tools(&peer, Some(params), RequestOptions::default()).await?;
            tools.extend(page.tools);
            match page.next_cursor {
                None => break,
                Some(next) if !cursors.insert(next.clone()) => {
                    return Err(McpError::InvalidCatalog(format!(
                        "server repeated pagination cursor '{next}'"
                    )));
                }
                Some(next) => cursor = Some(next),
            }
        }
        Self::from_catalog(peer, tools)
    }

    /// Bind an already-fetched catalog to `peer`.
    ///
    /// Use this to reuse a catalog the application has cached for the same
    /// server and caller or credential context. The application must ensure the
    /// catalog matches the peer's authorization context; this method does not
    /// verify that association. Fails if a tool name is empty or repeated.
    pub fn from_catalog<I>(peer: Peer<RoleClient>, tools: I) -> Result<Self, McpError>
    where
        I: IntoIterator<Item = rmcp::model::Tool>,
    {
        let tools = tools
            .into_iter()
            .map(|remote| McpTool {
                name: remote.name.to_string(),
                remote,
                schema: Arc::new(std::sync::OnceLock::new()),
            })
            .collect::<Vec<_>>();
        check_names(&tools)?;
        Ok(Self {
            peer,
            tools: tools.into(),
            schema_processor: Arc::new(SchemaProcessor::default()),
        })
    }

    /// Share a schema-work limit across catalogs or customize its concurrency.
    ///
    /// Compiled schemas remain reusable. The supplied processor governs future
    /// compilation and result validation; clones share that processor.
    pub fn with_schema_processor(mut self, processor: SchemaProcessor) -> Self {
        self.schema_processor = Arc::new(processor);
        self
    }

    /// Keep only the tools for which `keep` returns `true`.
    pub fn filter<F>(self, mut keep: F) -> Self
    where
        F: FnMut(&rmcp::model::Tool) -> bool,
    {
        let tools = self
            .tools
            .iter()
            .filter(|tool| keep(&tool.remote))
            .cloned()
            .collect::<Vec<_>>();
        Self {
            peer: self.peer,
            tools: tools.into(),
            schema_processor: self.schema_processor,
        }
    }

    /// Choose the name each tool is advertised to the model under.
    ///
    /// Calls are still sent to the server under the tool's own name. Use this
    /// to prefix tools from several servers, or to keep names a model or
    /// prompt already relies on. Fails if two tools end up with the same name
    /// or a name is empty.
    pub fn rename<F>(self, mut rename: F) -> Result<Self, McpError>
    where
        F: FnMut(&rmcp::model::Tool) -> String,
    {
        let tools = self
            .tools
            .iter()
            .map(|tool| McpTool {
                name: rename(&tool.remote),
                remote: tool.remote.clone(),
                schema: Arc::new(std::sync::OnceLock::new()),
            })
            .collect::<Vec<_>>();
        check_names(&tools)?;
        Ok(Self {
            peer: self.peer,
            tools: tools.into(),
            schema_processor: self.schema_processor,
        })
    }

    /// The session calls are sent on.
    pub fn peer(&self) -> &Peer<RoleClient> {
        &self.peer
    }

    /// Number of tools in the catalog.
    pub fn len(&self) -> usize {
        self.tools.len()
    }

    /// Whether the catalog is empty.
    pub fn is_empty(&self) -> bool {
        self.tools.is_empty()
    }

    /// Whether `name` is a tool in this catalog, by its advertised name.
    ///
    /// Applications combining several catalogs, or a catalog with local tools,
    /// use this to route a model's tool call.
    pub fn contains(&self, name: &str) -> bool {
        self.find(name).is_some()
    }

    /// The server's declaration of the tool advertised as `name`, including
    /// its title, annotations and output schema.
    pub fn remote_tool(&self, name: &str) -> Option<&rmcp::model::Tool> {
        self.find(name).map(|tool| &tool.remote)
    }

    /// The catalog as handler-free tool definitions, in server order.
    pub fn definitions(&self) -> Vec<ToolDefinition> {
        self.tools
            .iter()
            .map(|tool| ToolDefinition {
                name: tool.name.clone(),
                ..tool_definition(&tool.remote)
            })
            .collect()
    }

    /// The catalog as executable [`Tool`]s for the auto-executing request
    /// methods.
    ///
    /// Each tool calls the server through this catalog's peer. Inside the tool
    /// loop every failure is reported to the model, as for any tool handler:
    /// an `isError` result is sent as returned, and an [`McpError`] is sent as
    /// a tool error describing it.
    pub fn tools(&self) -> Vec<Tool> {
        self.tools
            .iter()
            .map(|tool| {
                let catalog = self.clone();
                let name = tool.name.clone();
                Tool::from_definition(
                    ToolDefinition {
                        name: tool.name.clone(),
                        ..tool_definition(&tool.remote)
                    },
                    move |arguments, _ctx| {
                        let catalog = catalog.clone();
                        let name = name.clone();
                        async move {
                            match catalog
                                .output(&name, arguments, None::<std::future::Pending<()>>)
                                .await
                            {
                                Ok(output) => Ok(output),
                                Err(error) => Ok(ToolOutput::error(serde_json::to_string(
                                    &serde_json::json!({ "error": error.to_string() }),
                                )?)),
                            }
                        }
                    },
                )
            })
            .collect()
    }

    /// Execute a tool call from the model and return the tool-result message.
    ///
    /// Arguments that are not a JSON object (or `null`) are rejected without
    /// contacting the server, as a tool-error message the model can correct.
    pub async fn call(&self, call: &ToolCall) -> Result<Message, McpError> {
        self.call_inner(call, None::<std::future::Pending<()>>)
            .await
    }

    /// [`call`](Self::call), abandoned when `cancelled` completes first.
    ///
    /// A call that was already sent is cancelled on the server with
    /// `notifications/cancelled`, and [`McpError::Cancelled`] is returned
    /// without waiting for that notification to be delivered. See the
    /// [module documentation](self#cancellation) for what cancellation does
    /// and does not guarantee.
    pub async fn call_until<C>(&self, call: &ToolCall, cancelled: C) -> Result<Message, McpError>
    where
        C: Future<Output = ()>,
    {
        self.call_inner(call, Some(cancelled)).await
    }

    async fn call_inner<C>(
        &self,
        call: &ToolCall,
        cancelled: Option<C>,
    ) -> Result<Message, McpError>
    where
        C: Future<Output = ()>,
    {
        let output = self
            .output(&call.name, call.arguments.clone(), cancelled)
            .await?;
        Ok(output.into_message(call.id.clone()))
    }

    /// Execute a catalog-routed call and preserve the complete MCP result.
    ///
    /// Names are checked against this catalog and mapped to the server's names.
    /// Successful results are validated against declared output schemas before
    /// return. Compilation, execution and validation share the supplied budget.
    /// Non-object arguments return [`McpError::InvalidArguments`] without dispatch.
    /// Model conversion is left to the caller; [`Self::call`] builds on this path.
    pub async fn call_result(
        &self,
        call: &ToolCall,
        options: RequestOptions,
    ) -> Result<CallToolResult, McpError> {
        self.call_result_until(call, options, std::future::pending())
            .await
    }

    /// [`Self::call_result`], abandoned when `cancelled` completes first.
    pub async fn call_result_until<C>(
        &self,
        call: &ToolCall,
        options: RequestOptions,
        cancelled: C,
    ) -> Result<CallToolResult, McpError>
    where
        C: Future<Output = ()>,
    {
        self.call_result_inner(&call.name, call.arguments.clone(), options, cancelled)
            .await
    }

    async fn call_result_inner<C>(
        &self,
        name: &str,
        arguments: serde_json::Value,
        options: RequestOptions,
        cancelled: C,
    ) -> Result<CallToolResult, McpError>
    where
        C: Future<Output = ()>,
    {
        let started = tokio::time::Instant::now();
        let deadline = options
            .timeout
            .and_then(|timeout| started.checked_add(timeout));
        let remaining = || RequestOptions {
            timeout: options
                .timeout
                .map(|timeout| timeout.saturating_sub(started.elapsed())),
        };
        let execute = async {
            let params = self.parameters(name, arguments)?;
            let tool = self.find(name).ok_or_else(|| McpError::ToolNotFound {
                name: name.to_owned(),
            })?;
            let schemas = tool.output_schemas(&self.schema_processor).await?;
            let result = call_tool(&self.peer, params, remaining()).await?;
            if let Some(schemas) = &schemas {
                self.schema_processor
                    .validate(schemas, name, &result, remaining())
                    .await?;
            }
            Ok(result)
        };
        let expired = async {
            if options.timeout.is_some_and(|timeout| timeout.is_zero()) {
                return;
            }
            match deadline {
                Some(deadline) => tokio::time::sleep_until(deadline).await,
                None => std::future::pending().await,
            }
        };
        tokio::select! {
            biased;
            () = cancelled => Err(McpError::Cancelled { tool: name.to_owned() }),
            () = expired => Err(McpError::Service(ServiceError::Timeout { timeout: options.timeout.unwrap_or_default() })),
            result = execute => match (result, options.timeout) {
                (Err(McpError::Service(ServiceError::Timeout { .. })), Some(timeout)) => Err(McpError::Service(ServiceError::Timeout { timeout })),
                (result, _) => result,
            },
        }
    }

    fn parameters(
        &self,
        name: &str,
        arguments: serde_json::Value,
    ) -> Result<CallToolRequestParams, McpError> {
        let tool = self.find(name).ok_or_else(|| McpError::ToolNotFound {
            name: name.to_string(),
        })?;
        let params = CallToolRequestParams::new(tool.remote.name.clone());
        match arguments {
            serde_json::Value::Object(arguments) => Ok(params.with_arguments(arguments)),
            serde_json::Value::Null => Ok(params),
            _ => Err(McpError::InvalidArguments {
                tool: name.to_owned(),
            }),
        }
    }

    async fn output<C>(
        &self,
        name: &str,
        arguments: serde_json::Value,
        cancelled: Option<C>,
    ) -> Result<ToolOutput, McpError>
    where
        C: Future<Output = ()>,
    {
        let cancelled = async {
            match cancelled {
                Some(cancelled) => cancelled.await,
                None => std::future::pending().await,
            }
        };
        let result = match self
            .call_result_inner(
                name,
                arguments.clone(),
                RequestOptions::default(),
                cancelled,
            )
            .await
        {
            Err(McpError::InvalidArguments { .. }) => return Ok(argument_error(name, &arguments)),
            other => other?,
        };
        let remote_name = self
            .remote_tool(name)
            .map_or(name, |tool| tool.name.as_ref());
        tool_output(remote_name, &result)
    }

    fn find(&self, name: &str) -> Option<&McpTool> {
        self.tools.iter().find(|tool| tool.name == name)
    }
}

fn check_names(tools: &[McpTool]) -> Result<(), McpError> {
    let mut seen = HashSet::with_capacity(tools.len());
    for tool in tools {
        if tool.name.trim().is_empty() {
            return Err(McpError::InvalidCatalog(format!(
                "tool '{}' has an empty name",
                tool.remote.name
            )));
        }
        if !seen.insert(tool.name.as_str()) {
            return Err(McpError::InvalidCatalog(format!(
                "tool name '{}' appears more than once",
                tool.name
            )));
        }
    }
    Ok(())
}

fn argument_error(name: &str, arguments: &serde_json::Value) -> ToolOutput {
    let kind = match arguments {
        serde_json::Value::Bool(_) => "boolean",
        serde_json::Value::Number(_) => "number",
        serde_json::Value::String(_) => "string",
        serde_json::Value::Array(_) => "array",
        serde_json::Value::Null | serde_json::Value::Object(_) => "object",
    };
    ToolOutput::error(
        serde_json::json!({
            "error": {
                "type": "tool_argument_validation",
                "tool": name,
                "retryable": true,
                "message": "Tool arguments failed validation. Call the tool again with corrected arguments.",
                "summary": format!("arguments must be a JSON object, not a {kind}"),
                "issues": [],
            }
        })
        .to_string(),
    )
}
